[package]
name = "rust-text-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
rand = "0.8.5"
thiserror = "1.0.52"
tokio = { version = "1.35.1", features = ["full"] }
